use_frameworks!

platform :ios, '10.0'

target 'TRVideoPlayer_Example' do
  pod 'TRVideoPlayer', :path => '../'

  target 'TRVideoPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
